import mongoose, { Document, Schema } from 'mongoose';

export interface IGitRepoMapping {
  name: string;
  repoUrl: string;
  branch: string;
  provider?: 'gitlab' | 'github';
  /** app = source code built by CI; gitops = manifests ArgoCD deploys from. */
  role?: 'app' | 'gitops';
}

export interface IK8sMapping {
  clusterName: string;
  namespaces: string[];
}

/** Public hostname of an environment, served through Cloudflare. */
export interface IEnvDns {
  hostname: string;
  connectorId: string;
  zoneId: string;
  zoneName: string;
  /** record = A/CNAME to an address you give (or the Ingress address); tunnel = through a Cloudflare Tunnel. */
  mode: 'record' | 'tunnel';
  /** record mode: IP or hostname the record points at; empty = the environment's Ingress address. */
  target: string;
  /** tunnel mode: the tunnel that serves it. */
  tunnelId: string;
  /** tunnel mode: in-cluster service and port; empty = the environment's first Service. */
  service: string;
  port: number;
  proxied: boolean;
  /** Generated by "Get random URL" (safe to replace with a new random name). */
  random?: boolean;
  updatedAt?: Date;
  updatedBy?: string;
}

/** Temporary public URL from a Cloudflare quick tunnel (trycloudflare.com); needs no domain or token. */
export interface IEnvPreview {
  url: string;
  startedAt?: Date;
  startedBy?: string;
}

export interface IArgoAppMapping {
  appName: string;
  targetNamespace: string;
  serverUrl?: string;
  /** Environment name shown in DevOps Intelligence (dev, qa, staging, prod…). Derived from the app name when empty. */
  environment?: string;
  /** Git branch of the app repo that deploys to this environment (branch-per-environment flow). */
  branch?: string;
  /** Deploys need an approved request. null/undefined = default (prod and production do). */
  requiresApproval?: boolean | null;
  dns?: IEnvDns | null;
  preview?: IEnvPreview | null;
}

/** Code quality and image scanning settings. */
export interface IProjectSecurity {
  sonarConnectorId?: string;
  /** Empty = derived from the project name. */
  sonarProjectKey?: string;
  /** Refuse promotions into gated environments (prod) while the quality gate fails. */
  blockOnQualityGate?: boolean;
  /** Refuse promotions into gated environments while the promoted image has critical CVEs. */
  blockOnCritical?: boolean;
  lastAnalysis?: { job: string; namespace: string; clusterName: string; projectKey: string; branch: string; startedAt: Date; startedBy: string } | null;
}

export interface IProject extends Document {
  name: string;
  description?: string;
  gitLabRepos: IGitRepoMapping[];
  gitopsPath?: string; // folder holding one overlay per environment, e.g. k8s/overlays
  kubernetesMappings: IK8sMapping[];
  argoApps: IArgoAppMapping[];
  security?: IProjectSecurity | null;
  active: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const ProjectSchema = new Schema<IProject>(
  {
    name: {
      type: String,
      required: true,
      unique: true,
      trim: true,
    },
    description: {
      type: String,
      default: '',
    },
    gitopsPath: { type: String, default: '' },
    gitLabRepos: [
      {
        name: { type: String, required: true },
        repoUrl: { type: String, required: true },
        branch: { type: String, default: 'main' },
        provider: { type: String, enum: ['gitlab', 'github'], default: 'gitlab' },
        role: { type: String, enum: ['app', 'gitops', ''], default: '' },
      },
    ],
    kubernetesMappings: [
      {
        clusterName: { type: String, required: true, default: 'minikube' },
        namespaces: { type: [String], default: ['default'] },
      },
    ],
    argoApps: [
      {
        appName: { type: String, required: true },
        targetNamespace: { type: String, default: 'default' },
        environment: { type: String, default: '' },
        branch: { type: String, default: '' },
        requiresApproval: { type: Boolean, default: null },
        dns: {
          type: new Schema(
            {
              hostname: { type: String, required: true },
              connectorId: { type: String, default: '' },
              zoneId: { type: String, default: '' },
              zoneName: { type: String, default: '' },
              mode: { type: String, enum: ['record', 'tunnel'], default: 'record' },
              target: { type: String, default: '' },
              tunnelId: { type: String, default: '' },
              service: { type: String, default: '' },
              port: { type: Number, default: 0 },
              proxied: { type: Boolean, default: true },
              random: { type: Boolean, default: false },
              updatedAt: { type: Date },
              updatedBy: { type: String, default: '' },
            },
            { _id: false }
          ),
          default: null,
        },
        preview: {
          type: new Schema({ url: { type: String, default: '' }, startedAt: { type: Date }, startedBy: { type: String, default: '' } }, { _id: false }),
          default: null,
        },
        serverUrl: { type: String, default: 'https://argocd.kubeorbit.local' },
      },
    ],
    security: {
      type: new Schema(
        {
          sonarConnectorId: { type: String, default: '' },
          sonarProjectKey: { type: String, default: '' },
          blockOnQualityGate: { type: Boolean, default: false },
          blockOnCritical: { type: Boolean, default: false },
          lastAnalysis: { type: Schema.Types.Mixed, default: null },
        },
        { _id: false }
      ),
      default: null,
    },
    active: {
      type: Boolean,
      default: true,
    },
  },
  { timestamps: true }
);

export const Project = mongoose.model<IProject>('Project', ProjectSchema);
